version: '3.1'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: POSTGRES_DB
    ports:
      - "5432:5432"
    volumes:
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
