definitions:
  server.CreateAuthorRequest:
    properties:
      name:
        type: string
    type: object
  server.CreateAuthorResponse:
    properties:
      author_id:
        example: 931bf3fe-1c11-4f55-962f-2d54bba78e28
        type: string
    type: object
  server.CreateBookRequest:
    properties:
      author_id:
        type: string
      title:
        type: string
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  title: Postgres Crud API
  version: "1.0"
paths:
  /author:
    post:
      consumes:
      - application/json
      description: creates a author with provided info
      parameters:
      - description: Author info
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/server.CreateAuthorRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/server.CreateAuthorResponse'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Create author
      tags:
      - authors
  /book:
    post:
      consumes:
      - application/json
      description: creates a book with provided info
      parameters:
      - description: Book info
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/server.CreateBookRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Create book
      tags:
      - books
swagger: "2.0"
