version: '3.1'

services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
      - "./postgres:/var/lib/postgresql/data"
  student-service:
    image: student-service:latest
    restart: always
    env_file:
      - student-service.env
    depends_on:
      - postgres
  teacher-service:
    image: teacher-service:latest
    restart: always
    env_file:
      - teacher-service.env
    depends_on:
      - postgres
  schedule-service:
    image: schedule-service:latest
    restart: always
    env_file:
      - schedule-service.env
    depends_on:
      - postgres
  journal-service:
    image: journal-service:latest
    restart: always
    env_file:
      - journal-service.env
    depends_on:
      - postgres
  api-gateway:
    image: api-gateway:latest
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - api-gateway.env
    depends_on:
      - student-service
      - teacher-service
      - schedule-service
      - journal-service