openapi: '2'
info:
  title: Edu CRM
  version: '1.0'
servers:
  - url: http://localhost:8080
paths:
  /subject:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
      responses:
        '201':
          description: A subject object
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: 00dfff52-8ab7-4b14-8074-a6001fc6dfb3
                    format: uuid
                  name:
                    type: string
                    example: Math
                  description:
                    type: string
                    example: Math is a good subject
